services:
  anvil:
    image: ghcr.io/foundry-rs/foundry:latest
    platform: linux/amd64
    command:
      - anvil --host 0.0.0.0 --block-time 2
    ports:
      - 8545

  foundry:
    platform: linux/amd64
    environment:
      - API_KEY_ETHERSCAN="" # env var is required, but value isn't used
      - API_KEY_ARBISCAN="" # env var is required, but value isn't used
      - API_KEY_OPTIMISTIC_ETHERSCAN="" # env var is required, but value isn't used
      - ETH_RPC_URL=http://anvil:8545
    depends_on:
      - anvil
    build:
      context: .
      dockerfile: Dockerfile

